packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@trpc/server": ^11.5.0
  better-auth: ^1.3.13
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  tsdown: ^0.15.5
  "@trpc/client": ^11.5.0
