packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': 11.5.0
  '@trpc/server': 11.5.0
  better-auth: 1.3.13
  dotenv: 17.2.2
  hono: 4.8.2
  tsdown: 0.15.5
  typescript: 5.8.2
  zod: 4.1.11

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
